### ISSUE TITLE
Missing classes in powerdata source

### ISSUE THREAD

**Issue by craigpnnl** [powerdata/com.powerdata.openpa#5]
Hello, 

It looks as if there are some missing powerdata classes in the source code.  The following
- import com.powerdata.pd3.Column;
- import com.powerdata.pd3.PDDB;
- import com.powerdata.pd3.PDDBException;
- import com.powerdata.pd3.View;

Are not available in the repository.

**Comment by cmosier** [comment]
Sorry about that.

My guess is that those were included accidentally during internal testing.  I can review it later tonight and provide a fix.

**Comment by cmosier** [comment]
The repository should now build properly.  Thanks.
