### ISSUE TITLE
Update to README doc

### ISSUE THREAD

**Issue by craigpnnl** [powerdata/com.powerdata.openpa#6]
The readme states that to open a model one should use PAModel.Open().

PAModel however is now an interface so I believe that to load a model from raw or directory you would need to use the PAModelI class, however I am not 100% sure.

So could you update the readme me with the best way to load either the cascadia system or the palco system.

Thanks

**Comment by cmosier** [comment]
As the README indicated, we basically re-implemented all of OpenPA recently, and the documentation is in progress.  There is a lot that is working, however, so hopefully much of the API will be sufficiently intuitive to make some progress.

I've updated the README to provide the very basics of getting Cascadia loaded and to do some basic operations.  Will work on the README and java doc as much as I can, so please just ask questions if you're stuck to help set priorirites.  

I updated the cascadia sample data that will be required for this to work.  Please download the latest from the link in the README.

I will put the PALCO model back as soon as I can.

Thanks.

**Comment by craigpnnl** [comment]
Thanks alot, this really helps :)
