### ISSUE TITLE
psse2csv and psse2psm

### ISSUE THREAD

**Issue by craigpnnl** [powerdata/com.powerdata.openpa#7]
With the removal of psseraw package, how should one go about converting from a raw psse file to the psm file format.  I know your readme says that converters will be coming soon, but doesn't these to classes (and the supporting files) allow that?  

Thanks

**Comment by cmosier** [comment]
Sorry for the inconvenience.  The psseraw directories were not supposed to deleted as part of the cleanup.

The package should build normally again.

**Comment by cmosier** [comment]
The psse2csv isn't used for OpenPA at this point.  Psse2psm is brand new (so is the CSV builder) and hasn't had much testing against real apps yet.  That will be occurring this month, but let us know if you run into any issues.

**Comment by craigpnnl** [comment]
Well I have a raw file that doesn't get converted correctly, however I am not sure if it is because of your software or the raw file itself ;)  I am able to load the updated cascadia system however.

**Comment by cmosier** [comment]
What version of PSS/e?

**Comment by craigpnnl** [comment]
I want to say 30, but with the people around here appending columns to generation values and other things I am not 100% confident that it is a valid PSS/e format.

I see that you have some auto detection of different formats.  I need to look at that code and see if I can figure out if it truly is a 30 or not.
